### ISSUE TITLE
Load settings easily

### ISSUE THREAD

**Issue by jmendezv** [dlemmermann/PreferencesFX#43] opened 2018-11-17 10:53 UTC
Hi,

I’m using PrefrerencesFX for the first time and I just wanted to load the setting on start up. Is it possible? How? I have pretty much the same questions than tobiasdiez.

Thanks

Pep

**Comment by martinfrancois** [comment] 2018-11-24 13:47
Hi @jmendezv 

It's easier than you think. You only need to supply a property when creating a setting and you need to make sure to already create the `PreferencesFx` object upon start up of your application. You don't have to call `preferencesFx.show()` yet. As soon as the `PreferencesFx` object is being created, it will automatically load all of the saved values via a binding that is being made to each of your defined `Setting`s.

Here an example: In your application, simply declare a property:
`StringProperty welcomeText = new SimpleStringProperty("Hello World");`
Then, create a `PreferencesFx` object, using that property in a setting:
```
PreferencesFx preferences = PreferencesFx.of(AppStarter.class,
        Category.of("General",
            Setting.of("Welcome Text", welcomeText)
        )
);
```
Now, when you call `preferences.show()`, the dialog of the preferences will be shown. You can change the value of the `Setting` there and when closing the dialog, the value is automatically being saved. You can then close your application and re-open it. You will notice that the last changed value is being loaded again.

Please tell me if this made it clear.

**Comment by jmendezv** [comment] 2018-11-25 17:53
Hi François,

You are very kind to take the time to answer. Yes it works :) However, when I cancel a preferencefx window the values get changed too when they shouldn’t!!!

I think that the ‘Close’ button should be something like ‘Accept’ and the ‘Cancel’ button should be something like ‘Close’ (and shouldn’t change the settings). Or am I doing something wrong.

By the way. Great job!!

Best

Pep

**Comment by martinfrancois** [comment] 2018-11-26 20:56
Hi Pep,
You're welcome. I'm glad it works! :)
This is something that has caused confusion in the past, I hope I can clear this behavior up:
- When the user changes a setting, the values of the property gets automatically updated as soon as the user changes it
- If the user presses close, the settings will be saved
- If the user presses cancel, the changes made since the opening of the preferences dialog are reverted

So for example, let's imagine the following scenario for "Close":
- The value of a setting is "Hello World".
- The user changes the value to "Hello"
- The property will be changed to "Hello" as well
- The user presses close
- The value "Hello" will be saved

Here a scenario for "Cancel":
- The value of a setting is "Hello World".
- The user changes the value to "Hello"
- The property will be changed to "Hello" as well
- The user presses cancel
- The property will be set back to "Hello World"

The idea behind it was, that if the user made some changes they don't want to keep, they can press the "Cancel" button and it will undo all of the changes they made since opening the preferences dialog. We chose the name "Close", because "Accept" or "Save" would imply that the changes are only applied when pressing the button, but we wanted to suggest that the changes are instantly being applied.

Thanks a lot for the praise 😃

Best,
François

**Comment by martinfrancois** [comment] 2018-12-17 19:40
Since there hasn't been any feedback in a while, I'm closing this, assuming the issue is resolved. Please reopen an issue if you still have any questions.

**Closed by martinfrancois** 2018-12-17 19:40 UTC
Labels: awaiting feedback, question
